"""Curated pilot: 32 distinct exercise families, not numeric variants."""

# slug, Chinese title, learning objective, topics, local difficulty
C_PILOT = [
    ("hello-world", "返回问候语", "从函数返回约定的问候字符串。", ["函数", "字符串"], "beginner"),
    ("leap", "判断公历闰年", "组合整除条件，正确处理世纪年。", ["条件分支", "逻辑运算"], "beginner"),
    ("difference-of-squares", "平方和与和的平方", "计算前 n 个自然数的两种平方结果及其差。", ["循环", "算术运算"], "beginner"),
    ("grains", "棋盘上的麦粒", "按翻倍规则计算指定格及棋盘总麦粒数。", ["整数类型", "位运算"], "beginner"),
    ("resistor-color", "电阻色环编码", "把电阻颜色映射到对应数值。", ["枚举", "数组"], "beginner"),
    ("collatz-conjecture", "考拉兹步数", "按奇偶规则迭代，统计到达 1 的步数。", ["循环", "条件分支"], "beginner"),
    ("queen-attack", "棋盘上的皇后", "根据坐标判断两枚皇后是否可以互相攻击。", ["结构体", "条件分支"], "beginner"),
    ("darts", "飞镖计分", "根据点到圆心的距离判断所在计分区域。", ["浮点数", "条件分支"], "beginner"),
    ("resistor-color-duo", "双环电阻数值", "组合前两个电阻色环表示的数字。", ["枚举", "数组"], "beginner"),
    ("hamming", "DNA 差异计数", "逐字符比较等长序列并统计不同位置。", ["字符串", "循环"], "beginner"),
    ("space-age", "换算行星年龄", "用给定公转周期把秒数换算成年龄。", ["枚举", "浮点数"], "beginner"),
    ("rna-transcription", "DNA 转录", "按固定碱基对应关系转换字符串。", ["字符串", "内存管理"], "beginner"),
    ("binary", "二进制字符串转换", "逐位解析二进制文本并计算整数值。", ["字符串", "进制"], "beginner"),
    ("eliuds-eggs", "统计二进制中的 1", "统计整数二进制表示中置位的位数。", ["位运算", "循环"], "beginner"),
    ("two-fer", "拼接问候语", "处理默认名字并拼接完整的输出字符串。", ["字符串", "指针"], "beginner"),
    ("raindrops", "按因数转换文本", "根据能否整除 3、5、7 生成对应文本。", ["条件分支", "字符串"], "beginner"),
    ("perfect-numbers", "判断完全数", "求真因子之和并判断数的类别。", ["循环", "边界条件"], "intermediate"),
    ("high-scores", "整理高分榜", "在分数数组中查找最新分数及最高分。", ["数组", "循环"], "beginner"),
    ("pangram", "判断全字母句", "忽略大小写，检查文本是否包含全部英文字母。", ["字符串", "数组"], "beginner"),
    ("resistor-color-trio", "三环电阻读数", "组合有效数字和倍率，返回电阻阻值信息。", ["结构体", "枚举"], "intermediate"),
    ("armstrong-numbers", "判断阿姆斯特朗数", "拆分十进制数位并验证幂次和。", ["循环", "算术运算"], "intermediate"),
    ("isogram", "判断无重复字母", "检查单词中的字母是否重复出现。", ["字符串", "数组"], "beginner"),
    ("binary-search", "有序数组二分查找", "在有序数组中缩小搜索区间并处理未命中情况。", ["数组", "指针", "边界条件"], "intermediate"),
    ("triangle", "判断三角形类别", "先验证边长，再区分等边、等腰和不等边三角形。", ["条件分支", "浮点数"], "beginner"),
]
CPP_PILOT = [
    ("reverse-string", "反转字符串", "使用 C++ 字符串接口返回逆序文本。", ["字符串", "迭代器"], "beginner"),
    ("secret-handshake", "解码握手信号", "把整数中的标志位转换为有序动作列表。", ["位运算", "容器"], "beginner"),
    ("isbn-verifier", "校验 ISBN 编码", "解析字符及校验位，判断 ISBN-10 是否有效。", ["字符串", "边界条件"], "intermediate"),
    ("luhn", "校验 Luhn 校验和", "处理数字文本并按位置累计校验和。", ["字符串", "循环"], "intermediate"),
    ("acronym", "提取首字母缩写", "识别单词边界并组合大写首字母。", ["字符串", "条件分支"], "beginner"),
    ("rotational-cipher", "字母轮转加密", "在保留大小写和非字母字符的前提下轮转字母。", ["字符", "取模运算"], "beginner"),
    ("run-length-encoding", "游程编码与解码", "把连续重复字符转换为计数表示并实现逆过程。", ["字符串", "循环"], "intermediate"),
    ("scrabble-score", "计算单词分数", "按字母分值表累计单词的总分。", ["字符串", "容器"], "beginner"),
]
PILOT = {(language, item[0]): dict(zip(("slug", "title", "summary", "topics", "difficulty"), item))
         for language, rows in (("c", C_PILOT), ("cpp", CPP_PILOT)) for item in rows}

# Canonical text: https://www.boost.org/LICENSE_1_0.txt
# Catch2's original copyright header is retained separately with every source.
BOOST_LICENSE = """Boost Software License - Version 1.0 - August 17th, 2003

Permission is hereby granted, free of charge, to any person or organization
obtaining a copy of the software and accompanying documentation covered by
this license (the "Software") to use, reproduce, display, distribute,
execute, and transmit the Software, and to prepare derivative works of the
Software, and to permit third-parties to whom the Software is furnished to
do so, all subject to the following:

The copyright notices in the Software and this entire statement, including
the above license grant, this restriction and the following disclaimer,
must be included in all copies of the Software, in whole or in part, and
all derivative works of the Software, unless such copies or derivative
works are solely in the form of machine-executable object code generated by
a source language processor.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
DEALINGS IN THE SOFTWARE.
"""
